package deepble.navigation;

import java.util.HashMap;

/**
 * This class includes the Proximity Profile attributes.
 */
public class ProximityGattAttributes {
    private static HashMap<String, String> attributes = new HashMap();
    public static String CLIENT_CHARACTERISTIC_CONFIG = "00002902-0000-1000-8000-00805f9b34fb";

    public static String DEEPBLE_SERVICE   = "9102d17a-26d4-4923-ae17-090a90e158b9";
    public static String IS_ANCHOR_BOOLEAN = "625f9034-2fde-41e6-84ab-c9bf66a5119f";
    public static String USER_DEFINED_NAME = "462c80fd-bb23-4e44-a005-01130427acc5";
    


    /* Custom UUIDs were generated by guidgenerator.com
     * They are NOT guaranteed to be unique, if somehow an application
     * is using one of these UUIDs, behavior will be undefined
     */
    static {	
        // Custom DeepBLE Services
        attributes.put("9102d17a-26d4-4923-ae17-090a90e158b9", "DeepBLE Service");
        
        // Custom DeepBLE Characteristics
        attributes.put("625f9034-2fde-41e6-84ab-c9bf66a5119f", "Is Anchor Boolean");
        attributes.put("462c80fd-bb23-4e44-a005-01130427acc5", "User Defined Name");
        
        // Generic Access Characteristics
        attributes.put("00002a29-0000-1000-8000-00805f9b34fb", "Manufacturer Name String");
    }

    public static String lookup(String uuid, String defaultName) {
        String name = attributes.get(uuid);
        return name == null ? defaultName : name;
    }
}
